shuf 1.7 It makes everything better.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8,50 +8,46 @@ cccheck() {
 cat << EOF > conftest.c
 int main(void){return 0;}
 EOF
-    "$CC" -o /dev/null conftest.c > /dev/null 2>&1
+    $CC -o conftest conftest.c > /dev/null 2>&1
     if [ $? -eq 0 ] ; then
-      rm -f conftest.c
-      cc="$CC"
-      cco="="
-      return 1
+      ./conftest
+      if [ $? -eq 0 ] ; then
+	rm -f conftest conftest.c
+	cc="$CC"
+	return 0
+      else
+	echo "could not build working executables"
+	echo "Please ensure your C compiler is a native compiler"
+	exit 1
+      fi
     else
-      rm -f conftest.c
-      cco="?="
+      rm -f conftest conftest.c
     fi
-  else
-    cco="?="
   fi
 
-  for compiler in cc clang gcc ; do
-    cat << EOF > conftest.c
-	int
-#if defined(__llvm__) && defined(__clang__)
-	c=0
-#elif defined(__GNUC__)
-	c=0
-#else
-	c=1
-#endif
-      ;
-      int main(void){return c;}
+  for compiler in cc clang pcc xlc gcc ; do
+cat << EOF > conftest.c
+int main(void){return 0;}
 EOF
 
-    "$compiler" -o conftest conftest.c > /dev/null 2>&1
+    $compiler -o conftest conftest.c > /dev/null 2>&1
 
     if [ $? -eq 0 ] ; then
       ./conftest
-      c=$?
-      rm -f conftest conftest.c
-
-      if [ $c -eq 0 ] ; then
-        cc="$compiler"
-        return 1
+      if [ $? -eq 0 ] ; then
+	rm -f conftest conftest.c
+	cc="$compiler"
+	return 0
+      else
+	echo "could not build working executables"
+	echo "Please ensure your C compiler is a native compiler"
+	exit 1
       fi
     else
-      rm -f conftest.c
+      rm -f conftest conftest.c
     fi
   done
-  return 0
+  return 1
 }
 
 arc4randomuniformcheck() {
@@ -62,10 +58,10 @@ EOF
   "$cc" $tflags -o /dev/null conftest.c > /dev/null 2>&1
   if [ $? -eq 0 ] ; then
     rm -f conftest.c
-    return 1
+    return 0
   else
     rm -f conftest.c
-    return 0
+    return 1
   fi
 }
 
@@ -77,26 +73,42 @@ EOF
   "$cc" $tflags -o /dev/null conftest.c > /dev/null 2>&1
   if [ $? -eq 0 ] ; then
     rm -f conftest.c
-    return 1
+    return 0
   else
     rm -f conftest.c
-    return 0
+    return 1
   fi
 }
 
 libbsdcheck() {
   cat << EOF > conftest.c
-#include <stdlib.h>
+#include <bsd/stdlib.h>
 int main(void){strtonum(NULL, 0, 0, NULL);return 0;}
 EOF
+  tincs="-I/usr/local/include -I/usr/pkg/include -I/opt/include"
   tlibs="-L/usr/local/lib -L/usr/pkg/lib -L/opt/lib -lbsd"
-  "$cc" $tflags -o /dev/null conftest.c $tlibs > /dev/null 2>&1
+  "$cc" $tincs $tflags -o /dev/null conftest.c $tlibs > /dev/null 2>&1
   if [ $? -eq 0 ] ; then
     rm -f conftest.c
-    return 1
+    return 0
   else
     rm -f conftest.c
+    return 1
+  fi
+}
+
+pledgecheck() {
+  cat << EOF > conftest.c
+#include <unistd.h>
+int main(void){pledge(NULL,NULL);return 0;}
+EOF
+  $cc $tflags -o conftest conftest.c > /dev/null 2>&1
+  if [ $? -eq 0 ] ; then
+    rm -f conftest conftest.c
     return 0
+  else
+    rm -f conftest conftest.c
+    return 1
   fi
 }
 
@@ -108,25 +120,37 @@ EOF
   "$cc" $tflags -o /dev/null conftest.c > /dev/null 2>&1
   if [ $? -eq 0 ] ; then
     rm -f conftest.c
-    return 1
+    return 0
   else
     rm -f conftest.c
-    return 0
+    return 1
   fi
 }
 
 prefix="/usr/local"
-target=`uname -m`
-cflags="-O2 -pipe"
+libs=""
+libbsd=0
+
+if [ ! -z "$CFLAGS" ] ; then
+  cflags="$CFLAGS"
+else
+  cflags=""
+fi
+
+if [ ! -z "$LDFLAGS" ] ; then
+  ldflags="$LDFLAGS"
+else
+  ldflags=""
+fi
 
 printf "checking for C compiler... "
 cccheck
 if [ $? -eq 0 ] ; then
+  echo "$cc"
+else
   echo "not found"
   echo "Please install a C compiler and re-run configure."
   exit 1
-else
-  echo "$cc"
 fi
 
 printf "checking for OS... "
@@ -141,58 +165,64 @@ fi
 printf "checking for arc4random_uniform... "
 arc4randomuniformcheck
 if [ $? -eq 0 ] ; then
-  pflags=" -DLIBBSD"
-  libs=" -lbsd"
-  echo "no"
-else
-  pflags=""
-  libs=""
   echo "yes"
+else
+  libbsd=1
+  echo "no"
 fi
 
 printf "checking for getprogname... "
 getprognamecheck
 if [ $? -eq 0 ] ; then
-  pflags=" -DLIBBSD"
-  libs=" -lbsd"
-  echo "no"
-else
   echo "yes"
+else
+  libbsd=1
+  echo "no"
+fi
+
+printf "checking for pledge... "
+pledgecheck
+if [ $? -eq 0 ] ; then
+  cflags="$cflags -DHAVE_PLEDGE"
+  echo "yes"
+else
+  echo "no"
 fi
 
 printf "checking for strtonum... "
 strtonumcheck
 if [ $? -eq 0 ] ; then
-  pflags=" -DLIBBSD"
-  libs=" -lbsd"
-  echo "no"
-else
   echo "yes"
+else
+  libbsd=1
+  echo "no"
 fi
 
-if [ ! -z "$libs" ] ; then
+if [ $libbsd -eq 1 ] ; then
   printf "checking for libbsd... "
   libbsdcheck
-  if [ $? -eq 0 ] ; then
+  if [ $? -ne 0 ] ; then
     echo "not found"
     echo "You need libbsd to build shuf!"
     exit 1
   fi
+  cflags="$cflags -DLIBBSD"
+  libs=" -lbsd"
 fi
 
 cat << EOF > Makefile
 # This Makefile automatically generated by configure.
 
-CC $cco		$cc
-CFLAGS ?=	-O2 -pipe
+CC =		$cc
+CFLAGS =	$cflags
 PREFIX ?=	/usr/local
 
 all:
-	\${CC} \${CFLAGS}$pflags \${LDFLAGS} -o shuf shuf.c$libs
+	\${CC} \${CFLAGS} \${LDFLAGS} -o shuf shuf.c$libs
 
 install:
-	install -c -S -s -m 755 shuf \${DESTDIR}\${PREFIX}/bin
-	install -c -S -m 644 shuf.1 \${DESTDIR}\${PREFIX}/man/man1
+	install -c -S -s -m 755 shuf \${PREFIX}/bin
+	install -c -S -m 644 shuf.1 \${PREFIX}/man/man1
 
 clean:
 	rm -f shuf shuf.core
